<?xml version="1.0" encoding="utf-8"?><Database Name="DB_PTUD_QLTV" Class="DB_PTUD_QLTVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.ChiTietMuonTra" Member="ChiTietMuonTras">
    <Type Name="ChiTietMuonTra">
      <Column Name="MaMuonTra" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DaTra" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayTra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MuonTra_ChiTietMuonTra" Member="MuonTra" ThisKey="MaMuonTra" OtherKey="MaMuonTra" Type="MuonTra" IsForeignKey="true" />
      <Association Name="Sach_ChiTietMuonTra" Member="Sach" ThisKey="MaSach" OtherKey="MaSach" Type="Sach" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DocGia" Member="DocGias">
    <Type Name="DocGia">
      <Column Name="MaDocGia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDocGia" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaThe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TheThuVien_DocGia" Member="TheThuVien" ThisKey="MaThe" OtherKey="MaThe" Type="TheThuVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MuonTra" Member="MuonTras">
    <Type Name="MuonTra">
      <Column Name="MaMuonTra" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaThe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayMuon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="MuonTra_ChiTietMuonTra" Member="ChiTietMuonTras" ThisKey="MaMuonTra" OtherKey="MaMuonTra" Type="ChiTietMuonTra" />
      <Association Name="NhanVien_MuonTra" Member="NhanVien" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="NhanVien" IsForeignKey="true" />
      <Association Name="TheThuVien_MuonTra" Member="TheThuVien" ThisKey="MaThe" OtherKey="MaThe" Type="TheThuVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="NhanVien_MuonTra" Member="MuonTras" ThisKey="MaNhanVien" OtherKey="MaNhanVien" Type="MuonTra" />
    </Type>
  </Table>
  <Table Name="dbo.Sach" Member="Saches">
    <Type Name="Sach">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BiaSach" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaTheLoai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NamXuatBan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoLuongSach" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Sach_ChiTietMuonTra" Member="ChiTietMuonTras" ThisKey="MaSach" OtherKey="MaSach" Type="ChiTietMuonTra" />
      <Association Name="Sach_SachTacGia" Member="SachTacGias" ThisKey="MaSach" OtherKey="MaSach" Type="SachTacGia" />
      <Association Name="TheLoai_Sach" Member="TheLoai" ThisKey="MaTheLoai" OtherKey="MaTheLoai" Type="TheLoai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SachTacGia" Member="SachTacGias">
    <Type Name="SachTacGia">
      <Column Name="MaSach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTacGia" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Sach_SachTacGia" Member="Sach" ThisKey="MaSach" OtherKey="MaSach" Type="Sach" IsForeignKey="true" />
      <Association Name="TacGia_SachTacGia" Member="TacGia" ThisKey="MaTacGia" OtherKey="MaTacGia" Type="TacGia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TacGia" Member="TacGias">
    <Type Name="TacGia">
      <Column Name="MaTacGia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="TacGia_SachTacGia" Member="SachTacGias" ThisKey="MaTacGia" OtherKey="MaTacGia" Type="SachTacGia" />
    </Type>
  </Table>
  <Table Name="dbo.TheLoai" Member="TheLoais">
    <Type Name="TheLoai">
      <Column Name="MaTheLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="TheLoai_Sach" Member="Saches" ThisKey="MaTheLoai" OtherKey="MaTheLoai" Type="Sach" />
    </Type>
  </Table>
  <Table Name="dbo.TheThuVien" Member="TheThuViens">
    <Type Name="TheThuVien">
      <Column Name="MaThe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayBatDau" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TheThuVien_DocGia" Member="DocGias" ThisKey="MaThe" OtherKey="MaThe" Type="DocGia" />
      <Association Name="TheThuVien_MuonTra" Member="MuonTras" ThisKey="MaThe" OtherKey="MaThe" Type="MuonTra" />
    </Type>
  </Table>
</Database>